# Generated by Django 6.0.8 on 2026-10-02 15:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("frame_version", models.CharField(default="dummy-enu-v1", max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                ("connection_id", models.UUIDField(blank=True, null=True)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
                ("revision", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("secret_hash", models.CharField(max_length=255)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="control.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField()),
                ("released", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="control.device"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ControlLease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="control.device"
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="control.queueentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("request_id", models.UUIDField()),
                ("connection_id", models.UUIDField()),
                ("frame_version", models.CharField(max_length=80)),
                ("target", models.JSONField()),
                ("status", models.CharField(default="pending_ack", max_length=30)),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="control.controllease"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="control.device"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "session_key", "request_id"), name="idempotent_submission"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending_ack", "accepted"])),
                        fields=("device",),
                        name="one_active_command",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DevicePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="control.device"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("device", "user"), name="device_user_unique")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="queueentry",
            constraint=models.UniqueConstraint(fields=("device", "user"), name="one_queue_entry"),
        ),
        migrations.AddConstraint(
            model_name="controllease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at", None)), fields=("device",), name="one_live_lease"
            ),
        ),
    ]
