# Generated by Django 6.0.8 on 2026-10-05 18:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionSlot",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device_id", models.UUIDField(null=True)),
                ("credential_id", models.UUIDField(null=True)),
                ("connection_id", models.UUIDField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="connection_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("legacy", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "credential",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="control.devicecredential"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Computer registration settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="registration_singleton"
                    )
                ],
            },
        ),
    ]
